theme: jekyll-theme-tactile

show_downloads: false

title: "Love Diary~~~~"
description: >
   JacarriChan's Love Diary~~~~.

permalink: /:year-:title/
paginate: 5
gems:
  - jekyll-paginate

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
  - Vagrantfile
